version: "3.9"

services:
  gateway:
    build:
      context: .
      dockerfile: ./services/gateway/Dockerfile
    env_file:
      - ./services/gateway/.env
    ports:
      - 3000:3000
    volumes:
      - ./.volumes/gateway/logs/:/app/logs/

  auth:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./services/auth/Dockerfile
    env_file:
      - ./services/auth/.env
    ports:
      - 3001:3001
    volumes:
      - ./.volumes/auth/logs/:/app/logs/

  workspace:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./services/workspace/Dockerfile
    env_file:
      - ./services/workspace/.env
    ports:
      - 3002:3002
    volumes:
      - ./.volumes/workspace/logs/:/app/logs/

  grading:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./services/grading/Dockerfile
    env_file:
      - ./services/grading/.env
    ports:
      - 3003:3003
    volumes:
      - ./.volumes/grading/logs/:/app/logs/
